# Generated by Django 5.1 on 2024-08-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sumRate',
            field=models.IntegerField(default=int),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='sumVote',
            field=models.IntegerField(default=int),
            preserve_default=False,
        ),
    ]
